import Header from '@/components/shared/Header';
import SideBar from '@/components/shared/SideBar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '홈페이지',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <SideBar />
      <div>{children}</div>
    </>
  );
}
