import { BrandCategoryNav } from '@/components/scissorsPage/BrandCategoryNav';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Scissors',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <BrandCategoryNav />
      <div>{children}</div>
    </>
  );
}
